# Generated by Django 5.0.3 on 2024-03-06 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=10, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.SmallIntegerField()),
                ('gear', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], max_length=1)),
                ('rent_per_day', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
